/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:61: warning: Compound cfgparams is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/etc/Tlahuizcalpan.xml:32: warning: member with no name found.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:49: warning: Member infname (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:52: warning: Member cffname (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:55: warning: Member trfname (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:58: warning: Member sgfname (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:74: warning: Member cfgvals (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:77: warning: Member latitude (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:78: warning: Member longitude (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:79: warning: Member elevation (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:80: warning: Member timezn[TZLEN] (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:83: warning: Member width (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:83: warning: Member height (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:84: warning: Member image (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:85: warning: Member imageseg (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:86: warning: Member imagecnv (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:89: warning: Member year (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:90: warning: Member month (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:91: warning: Member day (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:92: warning: Member hour (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:93: warning: Member minute (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:94: warning: Member sec (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:96: warning: Member jdn (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:102: warning: Member ccindex (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:105: warning: Member valores[6] (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:106: warning: Member reading (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:106: warning: Member idxrd (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:108: warning: Member locinfo (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:109: warning: Member imginfo (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:110: warning: Member phinfo (variable) of file cloudcover.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:377: warning: The following parameters of catchParams(int na, char *la[], char **inpfile, char **confile, char **trifile, char **segfile) are not documented:
  parameter 'inpfile'
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:449: warning: argument 'ipp' of command @param is not found in the argument list of catsearch(int t, const int carr[], int low, int upp)
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:449: warning: The following parameters of catsearch(int t, const int carr[], int low, int upp) are not documented:
  parameter 'upp'
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:681: warning: Unsupported xml/html tag <configuration> found
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:682: warning: Unsupported xml/html tag <segmented> found
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:683: warning: Unsupported xml/html tag <trimmed> found
/home/jose/Cielo/CloudCover/CloudCover-1.0/facade-src/geoinfo.c:51: warning: Member reading (variable) of file geoinfo.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/facade-src/geoinfo.c:51: warning: Member idxrd (variable) of file geoinfo.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/facade-src/geoinfo.c:52: warning: Member valores[4] (variable) of file geoinfo.c is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:35: warning: Member MAXFNLEN (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:37: warning: Member TZLEN (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:40: warning: Member ERR_NARGS (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:41: warning: Member ERR_INFIL (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:42: warning: Member ERR_CFFIL (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:43: warning: Member ERR_WTFIL (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:44: warning: Member ERR_WSFIL (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:45: warning: Member ERR_GINFO (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:46: warning: Member ERR_IINFO (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:49: warning: Member MSG_WTFIL (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:50: warning: Member MSG_WSFIL (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:51: warning: Member MSG_CCI1 (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:52: warning: Member MSG_CCI2 (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:171: warning: Member FALSE (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:172: warning: Member TRUE (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:175: warning: Member MSKFILE (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:176: warning: Member GPLFILE (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:177: warning: Member RBTRESH (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:178: warning: Member NEIGHBS (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:179: warning: Member VOTESFL (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:180: warning: Member AZIMUTH (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:181: warning: Member LATITUD (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:182: warning: Member LONGITU (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:183: warning: Member ELEVATI (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:184: warning: Member UTCZONE (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:187: warning: Member TAGMSK (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:188: warning: Member TAGLOC (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:189: warning: Member TAGAZI (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:190: warning: Member TAGTRE (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:191: warning: Member TAGCON (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:193: warning: Member OFFMSK (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:194: warning: Member OFFLOC (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:195: warning: Member OFFAZI (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:196: warning: Member OFFRBT (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:197: warning: Member OFFNSZ (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:198: warning: Member ATTRSZ (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:199: warning: Member OFFVTF (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:200: warning: Member ATTRVF (macro definition) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/include/cloudcover.h:71: warning: Member diagmsg[15] (variable) of file cloudcover.h is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:63: warning: Member rbtreshold (variable) of class cfgparams is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:65: warning: Member neighbsize (variable) of class cfgparams is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:67: warning: Member votes2flip (variable) of class cfgparams is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:69: warning: Member msfname[MAXFNLEN] (variable) of class cfgparams is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:71: warning: Member glfname[MAXFNLEN] (variable) of class cfgparams is not documented.
/home/jose/Cielo/CloudCover/CloudCover-1.0/clcv-src/cloudcover.c:73: warning: Member azimuth (variable) of class cfgparams is not documented.
